### ISSUE TITLE
MathInspector and an Anaconda Environment

### ISSUE THREAD

**Issue by OrbitalMechanic** [MathInspector/MathInspector#11]
Can one use an Anaconda environment from MathInspector?

Sam Dupree.

**Comment by MathInspector** [comment]
My guess is: yes it will work.  Is there something you are trying to do that is not working, or is this a general question?

I have to guess since I have never used anaconda before, but in principle, anything that works in python should work in math inspector.  If this is not the case, I consider it a bug.  There is possibly a conflict on the mac build with anaconda, due to the fact that the mac build is using python 3.7.6 and there is a known issue that was resolved in python 3.8.3.  I am currently working on some issues associated with upgrading the mac build to the latest python version.

So I took a quick look into anaconda, and it seems like its a package manager and has lots of stuff like numpy, scipy, PIL, skimage, and a number of other libraries that math inspector already comes with.  I think anything you install with `conda install` will be accessible for math inspector.

If you end up finding any bugs associated with anaconda, please let me know

**Comment by OrbitalMechanic** [comment]
Thank you for responding to my inquiry so quickly. The question I have 
at present is how does one get MathInspector to access the modules 
installed managed under conda (Anaconda)?

Sam Dupree.

**Comment by MathInspector** [comment]
Can you please try the following and let me know if it works:

```$ conda install mpld3```

then in math inspector

```>>> import mpld3```

I randomly picked the package mpld, you can replace mpld3 with any package and try the same thing.

I am starting to suspect that the built app will not be able to detect modules on your system which have been installed via `conda install`.  I tried downloading anaconda and now my environment is all messed up, whoops =P

It looks like what is going to happen is if I install all the dependencies for math inspector via `conda install` then everything will run properly from source and it will be able to access anaconda modules.

One of the most important parts of math inspector to me personally, is that it's 100% free.  After browsing the website for anaconda, I can see that it is not a free product in the same sense.  For this reason, I am very hesitant to support anaconda in math inspector, and would strongly prefer to create free versions of any tools that are useful for people instead of building in support for paid tools for a third party company.

**Comment by OrbitalMechanic** [comment]
Rather than using mpld3, I tried it with spiceypy. MathInspector 
responded that it couldn't find the module. This again leads me to ask 
that if one is using the app, how does one get it find my Anacodna 
directory?

Sam Dupree.

**Comment by Eri516** [comment]
I am confused, how do you work on here?

**Comment by MathInspector** [comment]
Thanks for checking that.

Have you tried running math inspector from the source code, or were you running the built app?

If you are running from source code and it's not working, I will be a little surprised.

At this time I am leaning heavily towards not supporting Anaconda.  I suspect there might be a number of underlying issues.  If you feel strongly that you would like to use anaconda in math inspector, I would be happy to work together in this thread to debug any issues.  Before proceeding, let's just make sure that you are running the app from source and have used `conda install` to install all of the dependencies listed in INSTALL.md, and confirm that the issue persists in this scenario.

**Comment by OrbitalMechanic** [comment]
I'm running the app as opposed to running the source. Something else I 
noticed in running the app: in the pull-down menu, the preference option 
is grayed-out. Is that correct, or is that because the present version 
(0.91) is a beta?

**Comment by MathInspector** [comment]
The "preferences" menu option is something that is being generated from MacOS, and I hadn't noticed that it was there before!  The reason it's greyed out is because I never implemented that menu option, so you are not missing out on anything.

I am going to close this issue, since the original question has been addressed, and for the sake of keeping everything well organized in the issue section.  Please feel free to open additional issues with any bugs/suggestions etc...
