### ISSUE TITLE
Tensorflow

### ISSUE THREAD

**Issue by shavedcow** [MathInspector/MathInspector#14]
I can't import tensorflow. I think this ide would be perfect for making ai and machine learning models in but I can't seem to be able to access the libraries that would be neccesary.

**Comment by MathInspector** [comment]
The first thing that occurs to me is: are you using the built app or running from source?

The built app is using python 3.7.6 on mac(for now), and 3.9.1 on windows.  In a situation where you are using the built app and have a different python version installed, math inspector will be unable to find the modules installed on your system.  In other words, the built app can only detect modules on your system which share the same python version the app was built with.

For this reason, I suspect it will work when running from source, but I'd like to confirm this and make sure there are no other issues associated with TensorFlow.  The nice thing about shipping the app with frozen python lib's is it makes it very easy to install, the problem is what we are seeing in this issue, where the user has a different version of python on their machine.

Another possible fix might be, to install python 3.7.6 (or 3.9.1 on windows) and then install TensorFlow for that version of python, then try importing it into math inspector.  This should work regardless of which version of python you actively use, as long as the files are somewhere on your system.

One possible solution for issues of this type, is to build the app with the required dependencies, in this case TensorFlow.  I am not super familiar with TensorFlow, but this is a possibility.

**Comment by shavedcow** [comment]
Ok, thank you for responding.
