### ISSUE TITLE
[Suggestion] Integration with Jupyter lab

### ISSUE THREAD

**Issue by Somiona** [MathInspector/MathInspector#15]
Thank you for bring this brilliant application to reality, and I think it will even better for (especially) demonstration and exploration usage if this can be integrated into jupyter lab, and make it possible to drag-and-drop code blocks directly in notebook.

**Comment by MathInspector** [comment]
Thanks for the suggestion!  After considering this request, I have decided at this time not to support a feature of this type.  The main reason is that math inspector already has its own system for saving and sharing projects, and I think the product will benefit from a focus on making that system as good as possible, instead of supporting third party tools which serve the same purpose.
