### ISSUE TITLE
console output redirection & escape chars

### ISSUE THREAD

**Issue by casperdcl** [MathInspector/MathInspector#24]
Sometimes console output is sent to the terminal used to launch `mathinspector` rather then the app's REPL:

```bash
$ python -m mathinspector

list in REPL, bar in terminal: 100%|██████████| 10/10 [00:00<00:00, 313007.76it/s]
```

![image](https://user-images.githubusercontent.com/10780059/108505794-dd258900-72af-11eb-8a50-ab228d0b4a1b.png)

```python
import sys
print("in REPL")
print("in REPL", file=sys.stderr)

from tqdm import trange
list(trange(10, desc="list in REPL, bar in terminal", file=sys.stderr))
```

Why is this the case?

**Comment by MathInspector** [comment]
Good question.  I will need to look into tqdm internals more closely to know for sure.  Here is my initial guess

In this file, the builtin print function is overridden:
https://github.com/MathInspector/MathInspector/blob/master/mathinspector/console/interpreter.py#L93

It also redirects `sys.displayhook` to the function self.write, which can be found here:
https://github.com/MathInspector/MathInspector/blob/master/mathinspector/console/interpreter.py#L177

At first I thought a solution might involve modifying the `self.write` function, now I am not so sure.

One thing that *might* be happening is
- mathinspector is launched by python
- before the app is instantiated, tqdm is imported, and access the normal builtin print function and stores a reference to it
- while App is being instantiated, the class Interpreter overrides the builtin print function
- part of tqdm is using the mathinspector override, the other part is holding on to the previous reference

Does this sound like it might be the root cause?  If not, I will need to understand a bit more about how tqdm prints to the console.

**Comment by casperdcl** [comment]
but `sys.stderr.write("in REPL\n")` works correctly

**Comment by MathInspector** [comment]
I'm going through the tqdm code now and noticed the `logger` module has been used.  I was able to reproduce the issue and am currently investigating ways to get this into the mathinspector REPL

**Comment by MathInspector** [comment]
I  managed to get tqdm to log into the mathinspector REPL, I put the changes in a new branch "dev", here is a link.  It's not totally working, but I think this is the first step of the solution to this bug

https://github.com/MathInspector/MathInspector/blob/dev/mathinspector/console/interpreter.py#L97

**Comment by casperdcl** [comment]
Yes seems to work.

Now there's a different issue which is supporting carriage return `\r` and even ASCII escape codes

**Comment by MathInspector** [comment]
> print("hello\rworld") doesn't quite work properly in the mathinspector REPL

Nice catch.  I am planning to get that working and dig into the tqdm issue to make sure everything is being properly overridden, see if I can get it to print the status bar like on the command line, and figure out if there are any deeper lessons to learn from this bug which can prevent future issues of this nature.

**Comment by casperdcl** [comment]
`sys.stderr`/`out` also have a `.flush()` method as well as a `.buffer` member (`BufferedWriter` which accepts `bytes` not `str`)

**Comment by MathInspector** [comment]
<img width="830" alt="Screen Shot 2021-02-23 at 3 40 32 PM" src="https://user-images.githubusercontent.com/60369559/108905273-8391c700-75ed-11eb-9cf3-d9fce8132272.png">

I'll point out in the PR where the code is that handles this, in case you are curious how I handled the /r flag and modified the system for hijacking stdout/stderr

**Comment by MathInspector** [comment]
I finally realized what I had done wrong by using the stream for stdin for stderr.  I know it's right now because it magically printed the beautiful white rectangle symbol instead of `#`, but what I **really** want to know is: how did it work before?

<img width="967" alt="Screen Shot 2021-02-25 at 9 05 34 PM" src="https://user-images.githubusercontent.com/60369559/109244742-3b210780-77ad-11eb-8f5f-df6fa3333da1.png">

**Comment by casperdcl** [comment]
No, if the stream is a proper file-like object `tqdm` will use unicode ("beautiful white rectangles") automatically instead of ASCII (`#`).
